<?php

## DANS SE FICHIER JE VOUDRAIS

# UN FORMULAIRE HTML QUI ME PERMET DE CREE UN PERSONNAGE EN CHOISSANT SON TYPE

# UN FORMULAIRE AVEC
# - UN SELECTEUR QUI ME PERMET DE SELECTIONER UN PERSONNAGE DISPONIBLE DANS LA BASE DE DONNEE
# - UN SELECTEUR QUI ME PERMET DE SELECTIONER UN AUTRE PERSONNAGE DISPONIBLE DANS LA BASE DE DONNEE
# UN BOUTON FIGHT

# LORSQUE L'ON CLIQUE SUR LE BOUTON FIGHT, ON ENVOIE UN FORMULAIRE POST

# DANS SE FORMULAIRE POST JE VEUX QUE VOUS RECUPERIEZ LES DEUX PERSONNAGE CHOISIS DANS LES SELECTEUR HTML
# RECUPERER L'ATK DES PERSONNAGES, SOUSTRAIRE L'ATK DU PERSONNAGE AU PV DE LAUTRE PERSONNAGE (et vice versa)
# ENSUITE AFFICHER
#  - 1ER PERSONNAGE A PERDU TANT DE PV / PV ACTUEL :
#  - 2EME PERSONNAGE A PERDU TANT DE PV / PV ACTUEL :